image: node:14

cache:
  paths:
    - node_modules/

stages:
    - build
    - deploy


build_staging:
    stage: build
    only:
        - staging
    cache:
        paths:
            - dist/
    script:
        - rm ./package-lock.json
        - npm install
        - ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer --progress=false
    artifacts:
        paths:
            - dist/

deploy_staging:
    stage: deploy
    only:
        - staging
    environment: staging
    script:
        - echo "No STAGING"


build_page:
    stage: build
    only:
        - main
    cache:
        paths:
            - dist/
    script:
        - echo "Test Key ${YOUTUBE_API_KEY}"
        - rm ./package-lock.json
        - npm install
        - npm run build:gl
        #- ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer --progress=false --base-href /angular/
    artifacts:
        paths:
            - dist/

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  # rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  only:
  - main
